### ISSUE TITLE
problems and errors

### ISSUE THREAD

**Issue by samuscero** [mcgillij/amdfan#35]
hello, good afternoon. the application does not work, the default fan curve or modifying the yaml file... the daemon command indicates an error.. the enable and star service does not apply, status indicates that the service is not active.. thank you very much for the help

![perfil amd](https://github.com/mcgillij/amdfan/assets/174037006/73b4766c-159f-486e-97b0-707c7f2471ad)
![pyton](https://github.com/mcgillij/amdfan/assets/174037006/54cd4da1-229e-466b-b5ae-d96f1654621a)
![service ](https://github.com/mcgillij/amdfan/assets/174037006/3a1c3bdf-007a-472e-b180-f49163990a82)

- AMDFAN version: 0.2.2  /  0.2.1
- GPU model: RX 7900GRE
- Kernel version: Linux 6.9.7-zen1-1-zen
- Distribution: Archlinux KDE PLASMA

**Comment by mcgillij** [comment]
![image](https://github.com/mcgillij/amdfan/assets/1703958/708e1222-5339-4a74-abbc-e237a286c0df)
This seems interesting I'm wondering argument is invalid. I'm on the same kernel version.

![image](https://github.com/mcgillij/amdfan/assets/1703958/9d319169-2471-43e1-9d9a-f3c4b7f6c3da)

I'll see if I can replicate it

**Comment by mcgillij** [comment]
if you just try to run the daemon manually (without systemd/ctl), is there any extra information printed out, do you get the same error?

`sudo amdfan daemon &`

**Comment by samuscero** [comment]
> if you just try to run the daemon manually (without systemd/ctl), is there any extra information printed out, do you get the same error?
> 
> `sudo amdfan  It is the same but errno 22 nothing changes... it will be possible compatibility error with python

**Comment by samuscero** [comment]
> if you just try to run the daemon manually (without systemd/ctl), is there any extra information printed out, do you get the same error?
> 
> `sudo amdfan daemon &`

It is the same but errno 22 nothing changes... it will be possible compatibility error with python?

sorry I closed the post my mistake

**Comment by mcgillij** [comment]
Are you able to run the set command? 
![image](https://github.com/mcgillij/amdfan/assets/1703958/01c062f5-98f3-4884-a851-bbc72dcc9e32)

Just trying to see if it's maybe the entrypoint into run_daemon that you are having issues with.

**Comment by samuscero** [comment]
> Are you able to run the set command?
same 

![amdfan comando](https://github.com/mcgillij/amdfan/assets/174037006/7996c139-686d-487d-a483-e062fde8ffc3)

**Comment by mcgillij** [comment]
do you have the default config in /etc/amdfan.yml?

**Comment by samuscero** [comment]
hi sorry for replying late  /etc/amdfan.yml      yes it is default now , but if you modify it the app does not take the changes

**Comment by mcgillij** [comment]
does `ls /sys/class/drm | grep "^card"` return anything when you run it?

**Comment by olielvewen** [comment]
Hi,
I've got a similar issue. (I think)
Since a while impossible to run amdfan and even, I've seen that today impossible to update it. But that another issue and not only for amdfan but for all aur program (clang=17. then I've the 18. installed).

Here what I 've done.

- AMDFan version:0.21-1
- GPU model: Rx 5500 XT
- Kernel version : 6.9.10-zen1-1-zen
- Distribution : Garuda KDE Plasma 6.1.3
- Python version : 3.12.4

``` 
olivier@vingilot 
╰─λ inxi -bz
System:
Kernel: 6.9.10-zen1-1-zen arch: x86_64 bits: 64
Desktop: KDE Plasma v: 6.1.3 Distro: Garuda Linux
Machine:
Type: Desktop Mobo: ASUSTeK model: ROG STRIX B450-F GAMING v: Rev 1.xx
serial: <superuser required> UEFI: American Megatrends v: 0207
date: 06/12/2018
CPU:
Info: 8-core AMD Ryzen 7 2700X [MT MCP] speed (MHz): avg: 2382
min/max: 2200/3700
Graphics:
Device-1: AMD Navi 14 [Radeon RX 5500/5500M / Pro 5500M] driver: amdgpu
v: kernel
Display: wayland server: X.org v: 1.21.1.13 with: Xwayland v: 24.1.1
compositor: kwin_wayland driver: X: loaded: amdgpu
unloaded: modesetting,radeon dri: radeonsi gpu: amdgpu
resolution: 1920x1200
API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.1.4-arch1.2
renderer: AMD Radeon RX 5500 XT (radeonsi navi14 LLVM 18.1.8 DRM 3.57
6.9.10-zen1-1-zen)
Network:
Device-1: Intel I211 Gigabit Network driver: igb
Device-2: Broadcom BCM4360 802.11ac Dual Band Wireless Network Adapter
driver: wl
Device-3: NetGear A6100 AC600 DB Wireless Adapter [Realtek RTL8811AU]
driver: N/A type: USB
Device-4: Belkin F7D1102 N150/Surf Micro Wireless Adapter v1000 [Realtek
RTL8188CUS] driver: rtl8192cu type: USB
Device-5: TP-Link 802.11ac WLAN Adapter driver: N/A type: USB
Drives:
Local Storage: total: 465.76 GiB used: 346.19 GiB (74.3%)
Info:
Memory: total: 32 GiB available: 31.27 GiB used: 5.26 GiB (16.8%)
Processes: 416 Uptime: 1h 33m Shell: fish inxi: 3.3.35
```

```
olivier@vingilot in ~ took 1s
✦3  ╰─λ glxinfo | grep AMD
Vendor: AMD (0x1002)
Device: AMD Radeon RX 5500 XT (radeonsi, navi14, LLVM 18.1.8, DRM 3.57, 6.9.10-zen1-1-zen) (0x7340)
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon RX 5500 XT (radeonsi, navi14, LLVM 18.1.8, DRM 3.57, 6.9.10-zen1-1-zen)
GL_AMD_conservative_depth, GL_AMD_depth_clamp_separate,
GL_AMD_draw_buffers_blend, GL_AMD_framebuffer_multisample_advanced,
GL_AMD_gpu_shader_int64, GL_AMD_multi_draw_indirect,
GL_AMD_performance_monitor, GL_AMD_pinned_memory,
GL_AMD_query_buffer_object, GL_AMD_seamless_cubemap_per_texture,
GL_AMD_shader_stencil_export, GL_AMD_shader_trinary_minmax,
GL_AMD_texture_texture4, GL_AMD_vertex_shader_layer,
GL_AMD_vertex_shader_viewport_index, GL_ANGLE_texture_compression_dxt3,
GL_AMD_conservative_depth, GL_AMD_depth_clamp_separate,
GL_AMD_draw_buffers_blend, GL_AMD_framebuffer_multisample_advanced,
GL_AMD_multi_draw_indirect, GL_AMD_performance_monitor,
GL_AMD_pinned_memory, GL_AMD_query_buffer_object,
GL_AMD_seamless_cubemap_per_texture, GL_AMD_shader_stencil_export,
GL_AMD_shader_trinary_minmax, GL_AMD_texture_texture4,
GL_AMD_vertex_shader_layer, GL_AMD_vertex_shader_viewport_index,
GL_AMD_framebuffer_multisample_advanced, GL_AMD_performance_monitor,
```

```
─olivier@vingilot in ~ as 🧙 took 20s
✦2 [🔴] × systemctl status amdfan
× amdfan.service - amdfan controller
Loaded: loaded (/usr/lib/systemd/system/amdfan.service; enabled; preset: disabled)
Active: failed (Result: exit-code) since Mon 2024-07-29 15:35:08 CEST; 17min ago
Duration: 32ms
Invocation: 53da9aff8bfa4ef6bd85cde6e03cc704
Main PID: 3825 (code=exited, status=1/FAILURE)

juil. 29 15:35:08 vingilot systemd[1]: amdfan.service: Scheduled restart job, restart counter is at 5.
juil. 29 15:35:08 vingilot systemd[1]: amdfan.service: Start request repeated too quickly.
juil. 29 15:35:08 vingilot systemd[1]: amdfan.service: Failed with result 'exit-code'.
juil. 29 15:35:08 vingilot systemd[1]: Failed to start amdfan controller.

╭─olivier@vingilot in ~ as 🧙 took 29ms
✦2 [🔴] × systemctl restart amdfan

╭─olivier@vingilot in ~ as 🧙 took 3s
✦2  ╰─λ systemctl status amdfan
× amdfan.service - amdfan controller
Loaded: loaded (/usr/lib/systemd/system/amdfan.service; enabled; preset: disabled)
Active: failed (Result: exit-code) since Mon 2024-07-29 15:52:34 CEST; 8s ago
Duration: 56ms
Invocation: 2756431a81dd416c92512f04715c04ce
Process: 37913 ExecStart=/usr/bin/amdfan --daemon (code=exited, status=1/FAILURE)
Main PID: 37913 (code=exited, status=1/FAILURE)

juil. 29 15:52:34 vingilot systemd[1]: amdfan.service: Scheduled restart job, restart counter is at 5.
juil. 29 15:52:34 vingilot systemd[1]: amdfan.service: Start request repeated too quickly.
juil. 29 15:52:34 vingilot systemd[1]: amdfan.service: Failed with result 'exit-code'.
juil. 29 15:52:34 vingilot systemd[1]: Failed to start amdfan controller.
```

```
╭─olivier@vingilot in ~ took 45ms
✦3  ╰─λ cat /usr/lib/systemd/system/amdfan.service
error: invalid value 'rules' for '--style <components>': Unknown style, 'rules'

For more information, try '--help'.

╭─olivier@vingilot in ~ took 3ms
✦3 [🔴] × sudo amdfan daemon &
[sudo] Mot de passe de olivier :
─olivier@vingilot in ~
✦5 [🔴] × ls /sys/class/drm | grep "^card"
╭─olivier@vingilot in ~ took 6ms
✦5 [[]|[🔴]] => 🔴ERROR ×
╭─olivier@vingilot in ~ took 6ms
✦5 [[]|[🔴]] => 🔴ERROR × sudo amdfan set --speed 100 --card0
[sudo] Mot de passe de olivier :
Traceback (most recent call last):
File "/usr/bin/amdfan", line 5, in <module>
from amdfan.amdfan import cli
ModuleNotFoundError: No module named 'amdfan'
```

And my config file by default
```
#Fan Control Matrix.
# [<Temp in C>,<Fanspeed in %>]
speed_matrix:
- [4, 4]
- [30, 33]
- [45, 50]
- [60, 66]
- [65, 69]
- [70, 75]
- [75, 89]
- [80, 100]

# Current Min supported value is 4 due to driver bug
#
# Optional configuration options
#
# Allows for some leeway +/- temp, as to not constantly change fan speed
# threshold: 4
#
# Frequency will change how often we probe for the temp
# frequency: 5
#
# While frequency and threshold are optional, I highly recommend finding
# settings that work for you. I've included the defaults I use above.
#
# cards:
# can be any card returned from `ls /sys/class/drm | grep "^card[[:digit:]]$"`
# - card0
```
By advance, thanks a lot for your help and also for your work. It is the only way I've found for having my GPU working.

**Comment by mcgillij** [comment]
@olielvewen 
> ─olivier@vingilot in ~
✦5 [🔴] × ls /sys/class/drm | grep "^card"

For `amdfan` to be able to control the fans of your card, the card device has to show up in the `/sys/class/drm` directory.

![image](https://github.com/user-attachments/assets/118a83f2-28b4-49e6-acaf-943a3b5c05cb)

The other issue of note is that you don't seem to have amdfan installed in the python env that's running.

![image](https://github.com/user-attachments/assets/9dd72b90-35f8-4d6a-90bd-d39fad7a33fb)

maybe you could track down if you have multiple python verisons/venvs or shims installed that you are maybe running from.

![image](https://github.com/user-attachments/assets/e95ef8be-8d36-468e-94b7-a4c2a0fb9f83)

Your files may look a bit different since you have an older version installed.

**Comment by olielvewen** [comment]
I should have precised that I'm using amdfan since two years ago without any problems. 
I'm running on Garuda which an nice derivative of archlinux.
I've installed it with yay for getting it on AUR.
And I've got the last python version.

``è
olivier@vingilot in ~
╰─λ ls /sys/class/drm/
lrwxrwxrwx    - root 29 juil. 17:53  card1 -> ../../devices/pci0000:00/0000:00:03.1/0000:09:00.0/0000:0a:00.0/0000:0b:00.0/drm/card1
lrwxrwxrwx    - root 29 juil. 17:53  card1-DP-1 -> ../../devices/pci0000:00/0000:00:03.1/0000:09:00.0/0000:0a:00.0/0000:0b:00.0/drm/card1/card1-DP-1
lrwxrwxrwx    - root 29 juil. 17:53  card1-DP-2 -> ../../devices/pci0000:00/0000:00:03.1/0000:09:00.0/0000:0a:00.0/0000:0b:00.0/drm/card1/card1-DP-2
lrwxrwxrwx    - root 29 juil. 17:53  card1-DP-3 -> ../../devices/pci0000:00/0000:00:03.1/0000:09:00.0/0000:0a:00.0/0000:0b:00.0/drm/card1/card1-DP-3
lrwxrwxrwx    - root 29 juil. 17:53  card1-HDMI-A-1 -> ../../devices/pci0000:00/0000:00:03.1/0000:09:00.0/0000:0a:00.0/0000:0b:00.0/drm/card1/card1-HDMI-A-1
lrwxrwxrwx    - root 29 juil. 17:53  renderD128 -> ../../devices/pci0000:00/0000:00:03.1/0000:09:00.0/0000:0a:00.0/0000:0b:00.0/drm/renderD128
.r--r--r-- 4,1k root 29 juil. 17:53  version

╭─olivier@vingilot in ~ took 5ms
╰─λ which python
/usr/bin/python

╭─olivier@vingilot in ~ took 2ms
╰─λ python
Python 3.12.4 (main, Jun  7 2024, 06:33:07) [GCC 14.1.1 20240522] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by olielvewen** [comment]
Amdfan is installed, impossible to update (and then to remove) thanks to an issue with clang. To be precise I've a superior version and this issue concerne all my aur packages used and installed.

**Comment by mazunki** [comment]
I believe the proper import there should be `from amdfan.__main__ import cli`

**Comment by mcgillij** [comment]
> I believe the proper import there should be `from amdfan.__main__ import cli`

I think he's got the version prior to that change installed since he mentions amdfan 0.2.1 and his service file has --daemon. So it seems to line up.

Can you import the amdfan module in your python env, so after typing python in your terminal can you do an `import amdfan`?

**Comment by olielvewen** [comment]
At first look, he doesn't know amdfan like he won't be installed.
nb: I've just open a terminal in my home not in a specific location.

```
╭─olivier@vingilot in ~ as 🧙 took 364ms
╰─λ python
Python 3.12.4 (main, Jun  7 2024, 06:33:07) [GCC 14.1.1 20240522] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import amdfan
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'amdfan'
```

BTW I've found a screenshot of my previous utilization of amdfan.

[url]https://i.postimg.cc/hGWjctZM/2022-08-12-15-16.png[/url]

**Comment by mazunki** [comment]
Can you display the value of `sys.path` (and potentially `env | grep PYTHON`)?

**Comment by olielvewen** [comment]
> Can you display the value of `sys.path` (and potentially `env | grep PYTHON`)?

How can i do that ?

**Comment by olielvewen** [comment]
Thanks a lot for the explanations.

```
╭─olivier@vingilot in ~
╰─λ env | grep PYTHON

╭─olivier@vingilot in ~ took 2ms
[[]|[🔴]] => 🔴ERROR × python
Python 3.12.4 (main, Jun  7 2024, 06:33:07) [GCC 14.1.1 20240522] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.path)
['', '/usr/lib/python312.zip', '/usr/lib/python3.12', '/usr/lib/python3.12/lib-dynload', '/usr/lib/python3.12/site-packages']
```
Another test which confirm what I was thinking:

```
╭─olivier@vingilot in ~
╰─λ env
MCFLY_SESSION_ID=JnPdVFR6WWJFXXJy8MfN2qbP
MCFLY_HISTFILE=/home/olivier/.local/share/fish/fish_history
SHLVL=1
PWD=/home/olivier
KONSOLE_DBUS_WINDOW=/Windows/1
COLORFGBG=15;0
CSF_DrawPluginDefaults=/usr/share/opencascade/resources/DrawResources
CSF_IGESDefaults=/usr/share/opencascade/resources/XSTEPResource
CSF_MIGRATION_TYPES=/usr/share/opencascade/resources/StdResource/MigrationSheet.txt
CSF_PluginDefaults=/usr/share/opencascade/resources/StdResource
CSF_SHMessage=/usr/share/opencascade/resources/SHMessage
CSF_ShadersDirectory=/usr/share/opencascade/resources/Shaders
CSF_TObjDefaults=/usr/share/opencascade/resources/StdResource
ICEAUTHORITY=/run/user/1000/iceauth_YZLTCy
PAM_KWALLET5_LOGIN=/run/user/1000/kwallet5.socket
CSF_XCAFDefaults=/usr/share/opencascade/resources/StdResource
CSF_XSMessage=/usr/share/opencascade/resources/XSMessage
COLORTERM=truecolor
DEBUGINFOD_URLS=https://debuginfod.archlinux.org
CSF_STEPDefaults=/usr/share/opencascade/resources/XSTEPResource
DESKTOP_SESSION=plasma
LOGNAME=olivier
MMGT_CLEAR=1
DRAWDEFAULT=/usr/share/opencascade/resources/DrawResources/DrawDefault
CSF_EXCEPTION_PROMPT=1
CSF_OCCTResourcePath=/usr/share/opencascade/resources
DRAWHOME=/usr/share/opencascade/resources/DrawResources
GTK2_RC_FILES=/etc/gtk-2.0/gtkrc:/home/olivier/.gtkrc-2.0:/home/olivier/.config/gtkrc-2.0
GTK_RC_FILES=/etc/gtk/gtkrc:/home/olivier/.gtkrc:/home/olivier/.config/gtkrc
HOME=/home/olivier
QT_WAYLAND_RECONNECT=1
SSH_AUTH_SOCK=/run/user/1000/gcr/ssh
SHELL_SESSION_ID=89f9cd0ee1ea4af9bc222ca36764e7d4
SHELL=/bin/bash
SYSTEMD_EXEC_PID=2359
LC_TIME=fr_FR.UTF-8
CSF_TObjMessage=/usr/share/opencascade/resources/TObj
XDG_SESSION_ID=2
KDE_FULL_SESSION=true
XDG_CONFIG_DIRS=/home/olivier/.config/kdedefaults:/etc/xdg
DISPLAY=:1
MAIL=/var/spool/mail/olivier
USER=olivier
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
LC_NUMERIC=fr_FR.UTF-8
MANPAGER=sh -c 'col -bx | bat -l man -p'
JOURNAL_STREAM=9:7771
HG=/usr/bin/hg
KONSOLE_DBUS_SESSION=/Sessions/1
WAYLAND_DISPLAY=wayland-0
CSF_StandardDefaults=/usr/share/opencascade/resources/StdResource
XDG_SEAT=seat0
TERM=xterm-256color
LC_ADDRESS=fr_FR.UTF-8
LC_TELEPHONE=fr_FR.UTF-8
MANAGERPID=1674
SESSION_MANAGER=local/vingilot:@/tmp/.ICE-unix/2280,unix/vingilot:/tmp/.ICE-unix/2280
KONSOLE_DBUS_SERVICE=:1.399
XDG_MENU_PREFIX=plasma-
LC_PAPER=fr_FR.UTF-8
CSF_LANGUAGE=us
STARSHIP_SHELL=fish
INVOCATION_ID=5fa6c2faad4344f38c4954c91a5f622a
KONSOLE_VERSION=240502
PROFILEHOME=
LANG=fr_FR.UTF-8
LC_IDENTIFICATION=fr_FR.UTF-8
LC_MEASUREMENT=fr_FR.UTF-8
STARSHIP_SESSION_KEY=1801420881307014
MEMORY_PRESSURE_WATCH=/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/session.slice/plasma-plasmashell.service/memory.pressure
CASROOT=/usr
LC_NAME=fr_FR.UTF-8
MOTD_SHOWN=pam
KDE_APPLICATIONS_AS_SCOPE=1
XDG_SESSION_DESKTOP=KDE
MEMORY_PRESSURE_WRITE=c29tZSAyMDAwMDAgMjAwMDAwMAA=
XDG_RUNTIME_DIR=/run/user/1000
WINDOWID=3
CSF_XmlOcafResource=/usr/share/opencascade/resources/XmlOcafResource
XDG_CURRENT_DESKTOP=KDE
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
XDG_SESSION_TYPE=wayland
XDG_VTNR=1
KDE_SESSION_UID=1000
GRADLE_HOME=/usr/share/java/gradle
LANGUAGE=fr_FR:fr
XDG_SESSION_CLASS=user
CSF_MDTVTexturesDirectory=/usr/share/opencascade/resources/Textures
XKB_DEFAULT_LAYOUT=fr
LC_MONETARY=fr_FR.UTF-8
KDE_SESSION_VERSION=6
XDG_ACTIVATION_TOKEN=kwin-68
XAUTHORITY=/run/user/1000/xauth_kVGOdo
QT_AUTO_SCREEN_SCALE_FACTOR=0
CSF_StandardLiteDefaults=/usr/share/opencascade/resources/StdResource
XKB_DEFAULT_VARIANT=azerty
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus

```

**Comment by mazunki** [comment]
could you show the following command:
`find /usr/lib/python3.12 -name '*amdfan*' -type d -exec ls -lr {} +`

**Comment by olielvewen** [comment]
```
╭─olivier@vingilot in ~
╰─λ find /usr/lib/python3.12 -name '*amdfan*' -type d -exec ls -lr {} +

╭─olivier@vingilot in ~ took 448ms
╰─λ
```
It is really mysterious

**Comment by mazunki** [comment]
i'm not familiar with garuda, but does `pacman -Ql amdfan` show you the list of files for the package?

**Comment by olielvewen** [comment]
Sorry for the delay, I've not seen your answer.

```
─olivier@vingilot in ~
╰─λ pacman -Ql amdfan
amdfan /usr/
amdfan /usr/bin/
amdfan /usr/bin/amdfan
amdfan /usr/lib/
amdfan /usr/lib/python3.11/
amdfan /usr/lib/python3.11/site-packages/
amdfan /usr/lib/python3.11/site-packages/amdfan-0.1.26.dist-info/
amdfan /usr/lib/python3.11/site-packages/amdfan-0.1.26.dist-info/LICENSE
amdfan /usr/lib/python3.11/site-packages/amdfan-0.1.26.dist-info/METADATA
amdfan /usr/lib/python3.11/site-packages/amdfan-0.1.26.dist-info/RECORD
amdfan /usr/lib/python3.11/site-packages/amdfan-0.1.26.dist-info/WHEEL
amdfan /usr/lib/python3.11/site-packages/amdfan-0.1.26.dist-info/entry_points.txt
amdfan /usr/lib/python3.11/site-packages/amdfan/
amdfan /usr/lib/python3.11/site-packages/amdfan/__init__.py
amdfan /usr/lib/python3.11/site-packages/amdfan/__pycache__/
amdfan /usr/lib/python3.11/site-packages/amdfan/__pycache__/__init__.cpython-311.opt-1.pyc
amdfan /usr/lib/python3.11/site-packages/amdfan/__pycache__/__init__.cpython-311.pyc
amdfan /usr/lib/python3.11/site-packages/amdfan/__pycache__/amdfan.cpython-311.opt-1.pyc
amdfan /usr/lib/python3.11/site-packages/amdfan/__pycache__/amdfan.cpython-311.pyc
amdfan /usr/lib/python3.11/site-packages/amdfan/amdfan.py
amdfan /usr/lib/python3.11/site-packages/amdfan/amdfan.service
amdfan /usr/lib/systemd/
amdfan /usr/lib/systemd/system/
amdfan /usr/lib/systemd/system/amdfan.service

```
amdfan is well installed and used .

**Comment by mazunki** [comment]
@olielvewen do you have `python3.11` as a command on your system? If so, try importing amdfan from that version instead

**Comment by olielvewen** [comment]
https://github.com/mcgillij/amdfan/issues/35#issuecomment-2259020337

No I have not. As you can see in my previous answer, I have python 3.12.4. 
Perhaps, the issue is here and you have pointed it.

**Comment by mazunki** [comment]
@olielvewen Different python versions can coexist, but I don't know the exact details on how this is handled on Arch and derivatives. I know you can install `python311` from the AUR, and this will fix your issue temporarily. I also believe simply reinstalling `amdfan` will trigger a build for the newer version of python (did you try that? if not, try it). 

@mcgillij Does the PKGBUILD specification support triggering reinstalls when some dependency (e.g python) is updated? I'm a little bit surprised this doesn't happen automatically for python builds.

**Comment by mcgillij** [comment]
re-installing should put it in the installed python's site-packages, the issue is def that it's installed in the wrong python's site-packages dir.

**Comment by olielvewen** [comment]
@mazunki 
I'm aware than several Python versions can coexist. Hovewer not on an derivative of Archlinux. And I was not aware that you have too old Python version on ..............AUR.

I can't upgrade and I think remove amdfan. At first look, I got an issue for all aur packages which needs clang in version egal to 17. 0.6Hovewer I have clang 18.1.8-2 installed. And I've found none informations about this.

```
yay
......
: 20 à mettre à jours/installer.%!(EXTRA string=paquets)
20  aur/amdfan                  0.1.26-1     -> 0.2.1-1
19  aur/ceph-libs               15.2.17-1    -> 18.2.2-4
18  aur/electron25              25.9.8-1     -> 25.9.8-6
17  aur/headsetcontrol          2.7.0-2      -> 3.0.0-4
16  aur/java11-openjfx          11.0.18.u1-1 -> 11.0.20.u1-1
15  aur/khtml                   5.113.0-1    -> 5.115.0-1
14  aur/kjs                     5.113.0-1    -> 5.115.0-1
13  aur/krunner5                5.115.0-1    -> 5.115.0-4
12  aur/latte-dock              0.10.9-1     -> 0.10.9-3
11  aur/metis                   5.1.0.p10-2  -> 5.2.1-2
10  aur/pcloud-drive            1.9.9-1      -> 1.14.6-1
9  aur/pyside2                 5.15.12-2    -> 5.15.13-2
8  aur/pyside2-tools           5.15.12-2    -> 5.15.13-2
7  aur/python-apscheduler      3.10.1-2     -> 3.10.4-2
6  aur/python-async_generator  1.10-8       -> 1.10-9
5  aur/python-jarowinkler      1.2.3-1      -> 2.0.1-2
4  aur/python-pyamdgpuinfo     2.1.3-1      -> 2.1.6-1
3  aur/python-shiboken2        5.15.12-2    -> 5.15.13-2
2  aur/qgpgme-qt5              1.23.2-1     -> 1.23.2-5
1  aur/streamlink-twitch-gui   2.2.0-1      -> 2.5.2-1
==> Paquets à exclure : (ex. "1 2 3", "1-3", "^4" ou nom du dépôt)
-> Exclure des paquets peut causer une mise à jour partielle et casser le système.
==>
-> could not find all required packages: clang =17.0.6
```

```
╭─olivier@vingilot in ~ as 🧙 took 27ms
╰─λ pacman -Qi clang
Nom                      : clang
Version                  : 18.1.8-2
Description              : C language family frontend for LLVM
Architecture             : x86_64
URL                      : https://clang.llvm.org/
Licences                 : Apache-2.0 WITH LLVM-exception
Groupes                  : --
Fournit                  : clang-analyzer=18.1.8  clang-tools-extra=18.1.8
Dépend de                : llvm-libs  gcc  compiler-rt
Dépendances opt.         : openmp: OpenMP support in clang with -fopenmp [installé]
python: for scan-view and git-clang-format [installé]
llvm: referenced by some clang headers [installé]
Requis par               : bcc  clazy  doxygen  lldb  openshadinglanguage  qtcreator  shiboken6
Optionnel pour           : kate  qt5-tools  qt6-tools
Est en conflit avec      : clang-analyzer  clang-tools-extra
Remplace                 : clang-analyzer  clang-tools-extra
Taille installée         : 210,70 MiB
Paqueteur                : Leonidas Spyropoulos <artafinde@archlinux.org>
Compilé le               : jeu. 25 juil. 2024 10:55:34
Installé le              : lun. 29 juil. 2024 15:40:57
Motif d’installation     : Installé comme dépendance d’un autre paquet
Script d’installation    : Non
Validé par               : Signature
```

**Comment by olielvewen** [comment]
I've tried to install python 3.11 without any success.

```
╭─olivier@vingilot in ~ took 1m37s
╰─λ yay -S python311
AUR Explicit (1): python311-3.11.9-2
:: (1/1) PKGBUILD téléchargé : python311
1 python311                       (Les fichiers de compilation existent)
==> Paquets à nettoyer avant compilation (cleanBuild) ?
==> [N]Aucun [A]Tous [Ab]Annuler [I]nstallés [No]nInstallés ou (1 2 3, 1-3, ^4)
==> n
1 python311                       (Les fichiers de compilation existent)
==> Afficher les diffs ?
==> [N]Aucun [A]Tous [Ab]Annuler [I]nstallés [No]nInstallés ou (1 2 3, 1-3, ^4)
==> n
==> Création du paquet python311 3.11.9-2 (ven. 02 août 2024 21:31:54)
==> Récupération des sources…
-> Téléchargement de Python-3.11.9.tar.xz…
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 19.2M  100 19.2M    0     0  13.7M      0  0:00:01  0:00:01 --:--:-- 13.7M
==> ATTENTION : Ignore la vérification des signatures PGP des fichiers sources.
==> Validation des fichiers source avec sha256sums…
Python-3.11.9.tar.xz ... Réussite
:: (1/1) Lecture de SRCINFO : python311
gpg: error reading key: Pas de clef publique
gpg: error reading key: Pas de clef publique

:: Clés PGP dont l'import est nécessaire :
-> 0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D, requis par : python311
-> E3FF2839C048B25C084DEBE9B26995E310250568, requis par : python311
:: Import ? [O/n] o
:: Import des clés avec gpg...
gpg: key B26995E310250568: 3 duplicate signatures removed
gpg: clef B26995E310250568 : clef publique « Łukasz Langa (GPG langa.pl) <lukasz@langa.pl> » importée
gpg: key 2D347EA6AA65421D: 3 duplicate signatures removed
gpg: clef 2D347EA6AA65421D : clef publique « Ned Deily (Python release signing key) <nad@python.org> » importée
gpg:       Quantité totale traitée : 2
gpg:                     importées : 2
==> Création du paquet python311 3.11.9-2 (ven. 02 août 2024 21:32:01)
==> Vérification des dépendances pour l’exécution…
==> Vérification des dépendances pour la compilation…
==> Récupération des sources…
-> Python-3.11.9.tar.xz trouvé
==> Validation des fichiers source avec sha256sums…
Python-3.11.9.tar.xz ... Réussite
==> Suppression du répertoire $srcdir/ existant…
==> Extraction des sources…
-> Extraction de Python-3.11.9.tar.xz avec bsdtar
==> Lancement de prepare()…
==> Les sources sont prêtes.
==> ERREUR : Cannot find the debugedit binary required for including source files in debug packages.
-> erreur lors de la construction : python311-exit status 15
-> Impossible d’installer les paquets suivants. Une intervention manuelle est requise :
python311 - exit status 15
```

**Comment by olielvewen** [comment]
I've tried to update amdfan but without any success.

```
╭─olivier@vingilot in ~ took 26s
[🔴] × yay -S amdfan
AUR Explicit (1): amdfan-0.2.1-1
:: PKGBUILD à jour, omission du téléchargement : amdfan
1 amdfan                           (Installé)(Les fichiers de compilation existent)
==> Paquets à nettoyer avant compilation (cleanBuild) ?
==> [N]Aucun [A]Tous [Ab]Annuler [I]nstallés [No]nInstallés ou (1 2 3, 1-3, ^4)
==> a
:: Suppression (1/1) : /home/olivier/.cache/yay/amdfan
HEAD est maintenant à 978034b updated to also work in gentoo / rc
Suppression de amdfan-0.1.26-1-any.pkg.tar.zst
Suppression de amdfan-0.1.26.tar.gz
Suppression de amdfan-0.1.28.tar.gz
Suppression de amdfan-0.2.1.tar.gz
Suppression de src/
1 amdfan                           (Installé)(Les fichiers de compilation existent)
==> Afficher les diffs ?
==> [N]Aucun [A]Tous [Ab]Annuler [I]nstallés [No]nInstallés ou (1 2 3, 1-3, ^4)
==> n
==> Création du paquet amdfan 0.2.1-1 (ven. 02 août 2024 21:36:56)
==> Récupération des sources…
-> Téléchargement de amdfan-0.2.1.tar.gz…
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 16957  100 16957    0     0  21430      0 --:--:-- --:--:-- --:--:-- 7611k
==> ATTENTION : Ignore la vérification des signatures PGP des fichiers sources.
==> Validation des fichiers source avec md5sums…
amdfan-0.2.1.tar.gz ... Réussite
:: (1/1) Lecture de SRCINFO : amdfan
==> Création du paquet amdfan 0.2.1-1 (ven. 02 août 2024 21:36:57)
==> Vérification des dépendances pour l’exécution…
==> Vérification des dépendances pour la compilation…
==> Récupération des sources…
-> amdfan-0.2.1.tar.gz trouvé
==> Validation des fichiers source avec md5sums…
amdfan-0.2.1.tar.gz ... Réussite
==> Suppression du répertoire $srcdir/ existant…
==> Extraction des sources…
-> Extraction de amdfan-0.2.1.tar.gz avec bsdtar
==> Les sources sont prêtes.
==> ERREUR : Cannot find the debugedit binary required for including source files in debug packages.
-> erreur lors de la construction : amdfan-exit status 15
-> Impossible d’installer les paquets suivants. Une intervention manuelle est requise :
amdfan - exit status 15
```

**Comment by mcgillij** [comment]
Well whatever you did to your system, doesn't seem great. Since it's already messed up, you can copy the amdfan files from your 3.11 site-packages or just symlink the directory in your 3.12 site-packages then you should at least be able to load it from there. I generally wouldn't recommend installing things by hand in places generally reserved for the package manager, but it seems you can't use it anymore.

**Comment by olielvewen** [comment]
I'm agree with you, I prefere installing softwares by the usual way. So, I will stop this until I found a proper way to install it. And you have reason, even  I can manage my system, I have an issue with Aur packages and I  must firstly resolved it before going to further. Thanks for your help, amdfan is a program that I love and I wish a lot of things for this great program which help a lot in the past.
